// FILE: src/components/bulk-folder-upload/theme.js

export function getColors(darkMode) {
  return darkMode
    ? {
        pageBg: "#202020",
        cardBg: "#353535",
        surfaceAlt: "#252525",
        greyBg: "#1d1d1d",
        greyBgHover: "#2d323c",
        cardBorder: "#1d1d1d",
        textPrimary: "#e6e8eb",
        textTertiary: "#8b93a1",
        accent: "#6a95f2",
        accentSoft: "#1c2740",
        success: "#3fca84",
        successSoft: "#12291f",
        danger: "#f0665f",
        dangerSoft: "#331a19",
      }
    : {
        pageBg: "#f4f5f7",
        cardBg: "#ffffff",
        surfaceAlt: "#fafbfc",
        greyBg: "#f1f2f4",
        greyBgHover: "#e9ebee",
        cardBorder: "#e3e5e8",
        textPrimary: "#1c2024",
        textTertiary: "#667085",
        accent: "#2f6fed",
        accentSoft: "#eef2ff",
        success: "#1a7f4e",
        successSoft: "#ecfdf3",
        danger: "#b3261e",
        dangerSoft: "#fef3f2",
      };
}

export function buildStyles(colors) {
  return {
    page: {
      minHeight: "100vh",
      width: "100%",
      maxWidth: "100vw",
      boxSizing: "border-box",
      overflowX: "hidden",
      background: colors.pageBg,
      color: colors.textPrimary,
      padding: "20px 16px",
      fontFamily:
        "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      transition: "background 150ms ease, color 150ms ease",
    },
    shell: {
      maxWidth: 1600,
      width: "100%",
      margin: "0 auto",
      boxSizing: "border-box",
    },
    header: {
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    title: {
      fontSize: 19,
      fontWeight: 650,
      margin: 0,
      letterSpacing: "-0.01em",
    },
    subtitle: { fontSize: 13, color: colors.textTertiary, margin: "3px 0 0" },
    tabBar: {
      display: "flex",
      gap: 4,
      marginBottom: 12,
      borderBottom: `1px solid ${colors.cardBorder}`,
    },
    tabBtn: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      padding: "9px 16px",
      fontSize: 13,
      fontWeight: 600,
      color: colors.textTertiary,
      background: "transparent",
      border: "none",
      borderBottom: "2px solid transparent",
      cursor: "pointer",
      transition: "color 120ms ease, border-color 120ms ease",
    },
    tabBtnActive: {
      color: colors.accent,
      borderBottomColor: colors.accent,
    },
    layout: {
      display: "grid",
      gridTemplateColumns: "minmax(0, 400px) 1fr",
      gap: 16,
      alignItems: "start",
      width: "100%",
      maxWidth: "100%",
    },
    leftCol: {
      display: "flex",
      flexDirection: "column",
      gap: 10,
      minWidth: 0,
      maxHeight: "calc(100vh - 170px)",
      overflowY: "auto",
      overflowX: "hidden",
      paddingRight: 6,
      scrollbarGutter: "stable",
    },
    card: {
      background: colors.cardBg,
      border: `1px solid ${colors.cardBorder}`,
      borderRadius: 12,
      padding: 12,
      minWidth: 0,
      boxSizing: "border-box",
    },
    input: {
      border: `1px solid ${colors.cardBorder}`,
      borderRadius: 8,
      padding: "8px 10px",
      fontSize: 13.5,
      color: colors.textPrimary,
      background: colors.surfaceAlt,
      width: "100%",
      minWidth: 0,
      boxSizing: "border-box",
    },
    detectedDtnBanner: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      fontSize: 12.5,
      color: colors.textPrimary,
      background: colors.accentSoft,
      border: `1px solid ${colors.accent}`,
      borderRadius: 8,
      padding: "8px 11px",
      minWidth: 0,
      boxSizing: "border-box",
    },
    detectedDtnBannerWarn: {
      background: colors.dangerSoft,
      borderColor: colors.danger,
      color: colors.danger,
    },
    detectedDtnBannerInfo: {
      background: colors.accentSoft,
      borderColor: colors.accent,
      color: colors.textPrimary,
    },
    detectedDtnBannerWarnSoft: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      fontSize: 12.5,
      color: colors.danger,
      background: colors.dangerSoft,
      border: `1px solid ${colors.danger}`,
      borderRadius: 8,
      padding: "8px 11px",
      minWidth: 0,
      boxSizing: "border-box",
    },
    batchIdText: {
      fontSize: 11,
      color: colors.textTertiary,
      margin: "10px 0 0",
    },
    logsWrap: {
      display: "flex",
      flexDirection: "column",
      gap: 10,
      width: "100%",
      maxWidth: 900,
    },
    logsFiltersRow: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 10,
      minWidth: 0,
    },
    logsList: {
      listStyle: "none",
      margin: 0,
      padding: 0,
      display: "flex",
      flexDirection: "column",
      gap: 6,
      maxHeight: "none",
    },
    logRow: {
      border: `1px solid ${colors.cardBorder}`,
      borderRadius: 8,
      padding: "9px 11px",
      display: "flex",
      flexDirection: "column",
      gap: 4,
      minWidth: 0,
      boxSizing: "border-box",
    },
    logRowActive: {
      background: colors.accentSoft,
      borderColor: colors.accent,
    },
    logRowTop: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      minWidth: 0,
    },
    logRowIcon: {
      color: colors.textTertiary,
      display: "flex",
      flexShrink: 0,
    },
    logRowFilename: {
      flex: 1,
      fontSize: 13,
      fontWeight: 600,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      minWidth: 0,
    },
    logRowMeta: {
      fontSize: 11.5,
      color: colors.textTertiary,
      lineHeight: 1.5,
    },
    logRowError: {
      fontSize: 11.5,
      color: colors.danger,
      background: colors.dangerSoft,
      borderRadius: 6,
      padding: "5px 8px",
      marginTop: 2,
    },
    logRowInfo: {
      fontSize: 11.5,
      color: colors.accent,
      background: colors.accentSoft,
      borderRadius: 6,
      padding: "5px 8px",
      marginTop: 2,
    },
    logRowLink: {
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      fontSize: 11.5,
      color: colors.accent,
      textDecoration: "none",
      marginTop: 2,
    },
    paginationRow: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      marginTop: 12,
    },
    pageBtn: {
      border: `1px solid ${colors.cardBorder}`,
      background: colors.greyBg,
      color: colors.textPrimary,
      fontSize: 12.5,
      fontWeight: 600,
      padding: "7px 16px",
      borderRadius: 999,
      cursor: "pointer",
    },
    pageIndicator: {
      fontSize: 12.5,
      fontWeight: 600,
      color: colors.textTertiary,
    },
    groupsHeaderRow: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "2px 2px 0",
    },
    groupsHeaderLabel: {
      fontSize: 12.5,
      fontWeight: 600,
      color: colors.textTertiary,
    },
    searchRow: { display: "flex", gap: 8, minWidth: 0 },
    searchBtn: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      border: "none",
      background: colors.accent,
      color: "#fff",
      borderRadius: 8,
      width: 38,
      flexShrink: 0,
      cursor: "pointer",
    },

    clearDateLink: {
      display: "flex",
      alignItems: "center",
      gap: 4,
      background: "none",
      border: "none",
      color: colors.danger,
      fontSize: 11.5,
      cursor: "pointer",
      padding: "6px 2px 0",
    },
    noResultsText: {
      fontSize: 12.5,
      color: colors.textTertiary,
      padding: "6px 4px 2px",
      margin: 0,
    },
    folderTree: {
      display: "flex",
      flexDirection: "column",
      gap: 4,
      minWidth: 0,
    },
    folderGroup: {
      display: "flex",
      flexDirection: "column",
      minWidth: 0,
    },
    folderHeader: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      width: "100%",
      padding: "7px 6px",
      background: "transparent",
      border: "none",
      borderRadius: 6,
      cursor: "pointer",
      fontSize: 12.5,
      fontWeight: 600,
      color: colors.textPrimary,
      textAlign: "left",
      minWidth: 0,
      boxSizing: "border-box",
    },

    batchHeader: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      width: "100%",
      padding: "10px 10px",
      background: colors.surfaceAlt,
      border: `1px solid ${colors.cardBorder}`,
      borderRadius: 8,
      cursor: "pointer",
      textAlign: "left",
      minWidth: 0,
      boxSizing: "border-box",
      flexWrap: "wrap",
    },
    batchHeaderInfo: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      gap: 2,
      minWidth: 0,
      overflow: "hidden",
    },
    batchHeaderTitle: {
      fontSize: 12.5,
      fontWeight: 700,
      color: colors.textPrimary,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    batchHeaderSub: {
      fontSize: 11,
      color: colors.textTertiary,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },

    dtnGroupWrap: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
      marginTop: 6,
    },
    dtnSubHeader: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      padding: "5px 6px",
      fontSize: 11.5,
      fontWeight: 700,
      color: colors.accent,
      background: colors.accentSoft,
      borderRadius: 6,
      marginLeft: 6,
    },
    folderLabel: {
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      minWidth: 0,
    },
    folderCount: {
      fontSize: 10.5,
      fontWeight: 600,
      color: colors.textTertiary,
      background: colors.greyBg,
      padding: "1px 6px",
      borderRadius: 999,
      flexShrink: 0,
    },
    fileItemNested: {
      marginLeft: 19,
      width: "calc(100% - 19px)",
    },
    dropzone: {
      borderWidth: "1.5px",
      borderStyle: "dashed",
      borderColor: colors.cardBorder,
      borderRadius: 12,
      padding: "14px 12px",
      textAlign: "center",
      cursor: "pointer",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: 4,
      background: colors.cardBg,
      color: colors.textTertiary,
      transition: "border-color 120ms ease, background 120ms ease",
      minWidth: 0,
      boxSizing: "border-box",
    },
    dropzoneActive: {
      borderColor: colors.accent,
      background: colors.accentSoft,
    },
    dropzoneText: {
      fontSize: 13,
      margin: "4px 0 0",
      color: colors.textPrimary,
    },
    dropzoneHint: { fontSize: 11.5, color: colors.textTertiary, margin: 0 },
    fileListCard: {
      background: colors.cardBg,
      border: `1px solid ${colors.cardBorder}`,
      borderRadius: 12,
      padding: 10,
      minWidth: 0,
      boxSizing: "border-box",
    },
    fileListHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      fontSize: 12,
      color: colors.textTertiary,
      marginBottom: 8,
      padding: "0 4px",
    },
    groupsHeaderActions: {
      display: "flex",
      alignItems: "center",
      gap: 12,
    },
    addFolderLink: {
      display: "flex",
      alignItems: "center",
      gap: 4,
      background: "none",
      border: "none",
      color: colors.accent,
      fontSize: 12,
      cursor: "pointer",
      padding: 0,
    },
    clearLink: {
      display: "flex",
      alignItems: "center",
      gap: 4,
      background: "none",
      border: "none",
      color: colors.danger,
      fontSize: 12,
      cursor: "pointer",
      padding: 0,
    },
    dtnGroupHeader: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      padding: "6px 6px",
      fontSize: 12.5,
      fontWeight: 700,
      color: colors.accent,
      borderBottom: `1px solid ${colors.cardBorder}`,
      marginBottom: 4,
    },
    dtnGroupLabel: {
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      minWidth: 0,
    },
    dtnGroupBody: {
      marginLeft: 6,
      paddingLeft: 10,
      borderLeft: `2px solid ${colors.cardBorder}`,
      display: "flex",
      flexDirection: "column",
      gap: 4,
      marginBottom: 8,
      minWidth: 0,
    },
    fileList: {
      listStyle: "none",
      margin: 0,
      padding: 0,
      display: "flex",
      flexDirection: "column",
      gap: 4,
      maxHeight: 260,
      overflowY: "auto",
      overflowX: "hidden",
      minWidth: 0,
    },
    fileItem: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      padding: "8px 8px",
      borderRadius: 8,
      cursor: "pointer",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "transparent",
      fontSize: 12.5,
      minWidth: 0,
      boxSizing: "border-box",
    },
    fileItemActive: {
      background: colors.accentSoft,
      borderColor: colors.accent,
    },
    fileItemIcon: {
      color: colors.textTertiary,
      display: "flex",
      flexShrink: 0,
    },
    fileItemName: {
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      minWidth: 0,
    },
    fileItemSize: { color: colors.textTertiary, fontSize: 11, flexShrink: 0 },
    fileItemRemove: {
      border: "none",
      background: "transparent",
      color: colors.textTertiary,
      cursor: "pointer",
      display: "flex",
      padding: 2,
      borderRadius: 4,
      flexShrink: 0,
    },
    errorBanner: {
      background: colors.dangerSoft,
      border: `1px solid ${colors.danger}`,
      color: colors.danger,
      fontSize: 12.5,
      padding: "9px 11px",
      borderRadius: 8,
      minWidth: 0,
      boxSizing: "border-box",
    },
    actions: { display: "flex", justifyContent: "flex-end" },
    primaryBtn: {
      border: "none",
      background: colors.accent,
      color: "#fff",
      fontSize: 13.5,
      fontWeight: 600,
      padding: "9px 18px",
      borderRadius: 8,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: 8,
      width: "100%",
      justifyContent: "center",
      boxSizing: "border-box",
    },
    btnDisabled: { opacity: 0.55, cursor: "not-allowed" },
    resultsCard: {
      background: colors.cardBg,
      border: `1px solid ${colors.cardBorder}`,
      borderRadius: 12,
      padding: 12,
      minWidth: 0,
      boxSizing: "border-box",
    },
    resultsSummary: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      fontSize: 12.5,
      flexWrap: "wrap",
    },
    resultsTotal: { fontWeight: 600 },
    badgeSuccess: {
      display: "inline-flex",
      alignItems: "center",
      gap: 3,
      background: colors.successSoft,
      color: colors.success,
      padding: "2px 8px",
      borderRadius: 999,
      fontSize: 11.5,
      fontWeight: 600,
      flexShrink: 0,
    },
    badgeFail: {
      display: "inline-flex",
      alignItems: "center",
      gap: 3,
      background: colors.dangerSoft,
      color: colors.danger,
      padding: "2px 8px",
      borderRadius: 999,
      fontSize: 11.5,
      fontWeight: 600,
      flexShrink: 0,
    },
    badgeInfo: {
      display: "inline-flex",
      alignItems: "center",
      gap: 3,
      background: colors.accentSoft,
      color: colors.accent,
      padding: "2px 8px",
      borderRadius: 999,
      fontSize: 11.5,
      fontWeight: 600,
      flexShrink: 0,
    },
    resultsErrList: {
      listStyle: "none",
      margin: "10px 0 0",
      padding: 0,
      display: "flex",
      flexDirection: "column",
      gap: 6,
    },
    resultsErrItem: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      fontSize: 12,
      minWidth: 0,
    },
    resultsErrMsg: {
      color: colors.textTertiary,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      minWidth: 0,
    },
    previewCol: {
      minHeight: 800,
      position: "sticky",
      top: 20,
      alignSelf: "start",
      maxHeight: "calc(100vh - 60px)",
      minWidth: 0,
    },
    previewCard: {
      background: colors.cardBg,
      border: `1px solid ${colors.cardBorder}`,
      borderRadius: 12,
      height: "100%",
      minHeight: 800,
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      minWidth: 0,
    },
    previewEmpty: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      color: colors.textTertiary,
      padding: 40,
      textAlign: "center",
    },
    previewEmptyText: { fontSize: 13, margin: 0, maxWidth: 260 },
    previewHeader: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      padding: "12px 14px",
      borderBottom: `1px solid ${colors.cardBorder}`,
      fontSize: 12.5,
      minWidth: 0,
    },
    previewHeaderIcon: {
      color: colors.textTertiary,
      display: "flex",
      flexShrink: 0,
    },
    previewHeaderName: {
      flex: 1,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      fontWeight: 600,
      minWidth: 0,
    },
    previewHeaderSize: { color: colors.textTertiary, flexShrink: 0 },
    previewOpenLink: {
      color: colors.accent,
      display: "flex",
      flexShrink: 0,
      textDecoration: "none",
    },
    previewBody: {
      flex: 1,
      display: "flex",
      background: colors.surfaceAlt,
      minWidth: 0,
    },
    previewFrame: {
      width: "100%",
      height: "100%",
      minHeight: 800,
      border: "none",
    },
    previewImageWrap: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: 20,
      minWidth: 0,
    },
    previewImage: {
      maxWidth: "100%",
      maxHeight: "520px",
      objectFit: "contain",
      borderRadius: 8,
    },
    previewUnsupported: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      color: colors.textTertiary,
      padding: 40,
      textAlign: "center",
    },
    previewUnsupportedTitle: {
      fontSize: 13,
      fontWeight: 600,
      color: colors.textPrimary,
      margin: 0,
    },
    previewUnsupportedHint: { fontSize: 12, margin: 0 },
    previewFooterMeta: {
      padding: "8px 14px",
      borderTop: `1px solid ${colors.cardBorder}`,
      fontSize: 11.5,
      color: colors.textTertiary,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    progressBarTrack: {
      height: 6,
      borderRadius: 999,
      background: colors.greyBg,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      background: colors.accent,
      transition: "width 300ms ease",
    },
  };
}