export const tableColumns = [
  { key: "dtn", label: "DTN", width: "100px", frozen: true },
  { key: "estCat", label: "Est. Category", width: "120px" },
  { key: "ltoComp", label: "LTO Company", width: "180px" },
  { key: "ltoAdd", label: "LTO Address", width: "350px" },
  { key: "eadd", label: "Email", width: "240px" },
  { key: "tin", label: "TIN", width: "200px" },
  { key: "contactNo", label: "Contact No.", width: "250px" },
  { key: "ltoNo", label: "LTO No.", width: "220px" },
  { key: "validity", label: "Validity", width: "150px" },
  { key: "prodBrName", label: "Brand Name", width: "200px" },
  { key: "prodGenName", label: "Generic Name", width: "350px" },
  { key: "prodDosStr", label: "Dosage Str.", width: "160px" },
  { key: "prodDosForm", label: "Dosage Form", width: "200px" },
  { key: "prodClassPrescript", label: "Prescription", width: "100px" },
  { key: "prodEssDrugList", label: "Essential Drug", width: "120px" },
  { key: "prodPharmaCat", label: "Pharma Cat.", width: "250px" },
  { key: "prodManu", label: "Manufacturer", width: "250px" },
  { key: "prodManuAdd", label: "Manufacturer Address", width: "350px" },
  { key: "prodManuTin", label: "Manufacturer TIN", width: "130px" },
  { key: "prodManuLtoNo", label: "Manufacturer LTO No.", width: "150px" },
  { key: "prodManuCountry", label: "Manufacturer Country", width: "150px" },
  { key: "prodTrader", label: "Trader", width: "180px" },
  { key: "prodTraderAdd", label: "Trader Address", width: "200px" },
  { key: "prodTraderTin", label: "Trader TIN", width: "130px" },
  { key: "prodTraderLtoNo", label: "Trader LTO No.", width: "150px" },
  { key: "prodTraderCountry", label: "Trader Country", width: "150px" },
  { key: "prodRepacker", label: "Repacker", width: "180px" },
  { key: "prodRepackerAdd", label: "Repacker Address", width: "200px" },
  { key: "prodRepackerTin", label: "Repacker TIN", width: "130px" },
  { key: "prodRepackerLtoNo", label: "Repacker LTO No.", width: "150px" },
  { key: "prodRepackerCountry", label: "Repacker Country", width: "150px" },
  { key: "prodImporter", label: "Importer", width: "180px" },
  { key: "prodImporterAdd", label: "Importer Address", width: "390px" },
  { key: "prodImporterTin", label: "Importer TIN", width: "130px" },
  { key: "prodImporterLtoNo", label: "Importer LTO No.", width: "150px" },
  { key: "prodImporterCountry", label: "Importer Country", width: "150px" },
  { key: "prodDistri", label: "Distributor", width: "180px" },
  { key: "prodDistriAdd", label: "Distributor Address", width: "390px" },
  { key: "prodDistriTin", label: "Distributor TIN", width: "130px" },
  { key: "prodDistriLtoNo", label: "Distributor LTO No.", width: "150px" },
  { key: "prodDistriCountry", label: "Distributor Country", width: "150px" },
  { key: "prodDistriShelfLife", label: "Shelf Life", width: "120px" },
  { key: "storageCond", label: "Storage Condition", width: "150px" },
  { key: "packaging", label: "Packaging", width: "400px" },
  { key: "suggRp", label: "Suggested RP", width: "120px" },
  { key: "noSample", label: "No. Sample", width: "100px" },
  { key: "expiryDate", label: "Expiry Date", width: "120px" },
  { key: "cprValidity", label: "CPR Validity", width: "120px" },
  { key: "regNo", label: "Registration No.", width: "150px" },
  { key: "appType", label: "Application Type", width: "120px" },
  { key: "motherAppType", label: "Mother App Type", width: "150px" },
  { key: "oldRsn", label: "Old RSN", width: "120px" },
  { key: "ammend1", label: "Amendment 1", width: "150px" },
  { key: "ammend2", label: "Amendment 2", width: "150px" },
  { key: "ammend3", label: "Amendment 3", width: "150px" },
  { key: "prodCat", label: "Product Category", width: "150px" },
  { key: "certification", label: "Certification", width: "150px" },
  { key: "fee", label: "Fee", width: "100px" },
  { key: "lrf", label: "LRF", width: "100px" },
  { key: "surc", label: "SURC", width: "100px" },
  { key: "total", label: "Total", width: "100px" },
  { key: "orNo", label: "OR No.", width: "200px" },
  { key: "dateIssued", label: "Date Issued", width: "120px" },
  { key: "dateReceivedFdac", label: "Date Received FDAC", width: "150px" },
  { key: "dateReceivedCent", label: "Date Received Central", width: "150px" },
  { key: "mo", label: "MO", width: "100px" },
  { key: "file", label: "File", width: "150px" },
  { key: "secpa", label: "SECPA", width: "120px" },
  { key: "secpaExpDate", label: "SECPA Exp Date", width: "150px" },
  { key: "secpaIssuedOn", label: "SECPA Issued On", width: "150px" },
  { key: "deckingSched", label: "Decking Schedule", width: "150px" },
  { key: "eval", label: "Evaluator", width: "120px" },
  { key: "dateDeck", label: "Date Deck", width: "120px" },
  { key: "remarks1", label: "Remarks 1", width: "200px" },
  { key: "dateRemarks", label: "Date Remarks", width: "120px" },
  { key: "class", label: "Class", width: "100px" },
  { key: "dateReleased", label: "Date Released", width: "120px" },
  { key: "typeDocReleased", label: "Type Doc Released", width: "150px" },
  { key: "attaReleased", label: "Atta Released", width: "150px" },
  { key: "cprCond", label: "CPR Condition", width: "200px" },
  { key: "cprCondRemarks", label: "CPR Cond Remarks", width: "400px" },
  { key: "cprCondAddRemarks", label: "CPR Cond Add Remarks", width: "200px" },
  { key: "appStatus", label: "App Status", width: "120px" },
  { key: "appRemarks", label: "App Remarks", width: "200px" },
  { key: "userUploader", label: "Uploader", width: "200px" },
  { key: "dateExcelUpload", label: "Date Upload", width: "220px" },
];
