export const mapDataItem = (item, index) => ({
  id: item.DB_ID ?? index + 1,
  dtn: item.DB_DTN ?? "N/A",
  processingType: item.DB_PROCESSING_TYPE ?? "Regular", 
  estCat: item.DB_EST_CAT ?? "N/A",
  ltoComp: item.DB_EST_LTO_COMP ?? "N/A",
  ltoAdd: item.DB_EST_LTO_ADD ?? "N/A",
  eadd: item.DB_EST_EADD ?? "N/A",
  tin: item.DB_EST_TIN ?? "N/A",
  contactNo: item.DB_EST_CONTACT_NO ?? "N/A",
  ltoNo: item.DB_EST_LTO_NO ?? "N/A",
  validity: item.DB_EST_VALIDITY ?? "N/A",
  prodBrName: item.DB_PROD_BR_NAME ?? "N/A",
  prodGenName: item.DB_PROD_GEN_NAME ?? "N/A",
  prodDosStr: item.DB_PROD_DOS_STR ?? "N/A",
  prodDosForm: item.DB_PROD_DOS_FORM ?? "N/A",
  prodClassPrescript: item.DB_PROD_CLASS_PRESCRIP ?? "N/A",
  prodEssDrugList: item.DB_PROD_ESS_DRUG_LIST ?? "N/A",
  prodPharmaCat: item.DB_PROD_PHARMA_CAT ?? "N/A",
  prodManu: item.DB_PROD_MANU ?? "N/A",
  prodManuAdd: item.DB_PROD_MANU_ADD ?? "N/A",
  prodManuTin: item.DB_PROD_MANU_TIN ?? "N/A",
  prodManuLtoNo: item.DB_PROD_MANU_LTO_NO ?? "N/A",
  prodManuCountry: item.DB_PROD_MANU_COUNTRY ?? "N/A",
  prodTrader: item.DB_PROD_TRADER ?? "N/A",
  prodTraderAdd: item.DB_PROD_TRADER_ADD ?? "N/A",
  prodTraderTin: item.DB_PROD_TRADER_TIN ?? "N/A",
  prodTraderLtoNo: item.DB_PROD_TRADER_LTO_NO ?? "N/A",
  prodTraderCountry: item.DB_PROD_TRADER_COUNTRY ?? "N/A",
  prodRepacker: item.DB_PROD_REPACKER ?? "N/A",
  prodRepackerAdd: item.DB_PROD_REPACKER_ADD ?? "N/A",
  prodRepackerTin: item.DB_PROD_REPACKER_TIN ?? "N/A",
  prodRepackerLtoNo: item.DB_PROD_REPACKER_LTO_NO ?? "N/A",
  prodRepackerCountry: item.DB_PROD_REPACKER_COUNTRY ?? "N/A",
  prodImporter: item.DB_PROD_IMPORTER ?? "N/A",
  prodImporterAdd: item.DB_PROD_IMPORTER_ADD ?? "N/A",
  prodImporterTin: item.DB_PROD_IMPORTER_TIN ?? "N/A",
  prodImporterLtoNo: item.DB_PROD_IMPORTER_LTO_NO ?? "N/A",
  prodImporterCountry: item.DB_PROD_IMPORTER_COUNTRY ?? "N/A",
  prodDistri: item.DB_PROD_DISTRI ?? "N/A",
  prodDistriAdd: item.DB_PROD_DISTRI_ADD ?? "N/A",
  prodDistriTin: item.DB_PROD_DISTRI_TIN ?? "N/A",
  prodDistriLtoNo: item.DB_PROD_DISTRI_LTO_NO ?? "N/A",
  prodDistriCountry: item.DB_PROD_DISTRI_COUNTRY ?? "N/A",
  prodDistriShelfLife: item.DB_PROD_DISTRI_SHELF_LIFE ?? "N/A",
  storageCond: item.DB_STORAGE_COND ?? "N/A",
  packaging: item.DB_PACKAGING ?? "N/A",
  suggRp: item.DB_SUGG_RP ?? "N/A",
  noSample: item.DB_NO_SAMPLE ?? "N/A",
  expiryDate: item.DB_EXPIRY_DATE ?? "N/A",
  cprValidity: item.DB_CPR_VALIDITY ?? "N/A",
  regNo: item.DB_REG_NO ?? "N/A",
  appType: item.DB_APP_TYPE ?? "N/A",
  motherAppType: item.DB_MOTHER_APP_TYPE ?? "N/A",
  oldRsn: item.DB_OLD_RSN ?? "N/A",
  ammend1: item.DB_AMMEND1 ?? "N/A",
  ammend2: item.DB_AMMEND2 ?? "N/A",
  ammend3: item.DB_AMMEND3 ?? "N/A",
  prodCat: item.DB_PROD_CAT ?? "N/A",
  certification: item.DB_CERTIFICATION ?? "N/A",
  fee: item.DB_FEE ?? "N/A",
  lrf: item.DB_LRF ?? "N/A",
  surc: item.DB_SURC ?? "N/A",
  total: item.DB_TOTAL ?? "N/A",
  orNo: item.DB_OR_NO ?? "N/A",
  dateIssued: item.DB_DATE_ISSUED ?? "N/A",
  dateReceivedFdac: item.DB_DATE_RECEIVED_FDAC ?? "N/A",
  dateReceivedCent: item.DB_DATE_RECEIVED_CENT ?? "N/A",
  mo: item.DB_MO ?? "N/A",
  file: item.DB_FILE ?? "N/A",
  secpa: item.DB_SECPA ?? "N/A",
  secpaExpDate: item.DB_SECPA_EXP_DATE ?? "N/A",
  secpaIssuedOn: item.DB_SECPA_ISSUED_ON ?? "N/A",
  deckingSched: item.DB_DECKING_SCHED ?? "N/A",
  eval: item.DB_EVAL ?? "N/A",
  dateDeck: item.DB_DATE_DECK ?? "N/A",
  remarks1: item.DB_REMARKS_1 ?? "N/A",
  dateRemarks: item.DB_DATE_REMARKS ?? "N/A",
  class: item.DB_CLASS ?? "N/A",
  dateReleased: item.DB_DATE_RELEASED ?? "N/A",
  typeDocReleased: item.DB_TYPE_DOC_RELEASED ?? "N/A",
  attaReleased: item.DB_ATTA_RELEASED ?? "N/A",
  cprCond: item.DB_CPR_COND ?? "N/A",
  cprCondRemarks: item.DB_CPR_COND_REMARKS ?? "N/A",
  cprCondAddRemarks: item.DB_CPR_COND_ADD_REMARKS ?? "N/A",
  appStatus: item.DB_APP_STATUS ?? "N/A",
  appRemarks: item.DB_APP_REMARKS ?? "N/A",
  trash: item.DB_TRASH ?? "N/A",
  trashDateEncoded: item.DB_TRASH_DATE_ENCODED ?? "N/A",
  userUploader: item.DB_USER_UPLOADER ?? "N/A",
  dateExcelUpload: item.DB_DATE_EXCEL_UPLOAD ?? "N/A",
  pharmaProdCat: item.DB_PHARMA_PROD_CAT ?? "N/A",
  pharmaProdCatLabel: item.DB_PHARMA_PROD_CAT_LABEL ?? "N/A",
  isInPm: item.DB_IS_IN_PM ?? "N/A",

  // ✅ NEW: Timeline Citizen Charter field
  dbTimelineCitizenCharter: item.DB_TIMELINE_CITIZEN_CHARTER ?? null,

  // Application Delegation Fields
  decker: item.application_delegation?.DB_DECKER ?? "N/A",
  deckerDecision: item.application_delegation?.DB_DECKER_DECISION ?? "N/A",
  deckerRemarks: item.application_delegation?.DB_DECKER_REMARKS ?? "N/A",
  dateDeckedEnd: item.application_delegation?.DB_DATE_DECKED_END ?? "N/A",

  evaluator: item.application_delegation?.DB_EVALUATOR ?? "N/A",
  evalDecision: item.application_delegation?.DB_EVAL_DECISION ?? "N/A",
  evalRemarks: item.application_delegation?.DB_EVAL_REMARKS ?? "N/A",
  dateEvalEnd: item.application_delegation?.DB_DATE_EVAL_END ?? "N/A",

  checker: item.application_delegation?.DB_CHECKER ?? "N/A",
  checkerDecision: item.application_delegation?.DB_CHECKER_DECISION ?? "N/A",
  checkerRemarks: item.application_delegation?.DB_CHECKER_REMARKS ?? "N/A",
  dateCheckerEnd: item.application_delegation?.DB_DATE_CHECKER_END ?? "N/A",

  supervisor: item.application_delegation?.DB_SUPERVISOR ?? "N/A",
  supervisorDecision:
    item.application_delegation?.DB_SUPERVISOR_DECISION ?? "N/A",
  supervisorRemarks:
    item.application_delegation?.DB_SUPERVISOR_REMARKS ?? "N/A",
  dateSupervisorEnd:
    item.application_delegation?.DB_DATE_SUPERVISOR_END ?? "N/A",

  qa: item.application_delegation?.DB_QA ?? "N/A",
  qaDecision: item.application_delegation?.DB_QA_DECISION ?? "N/A",
  qaRemarks: item.application_delegation?.DB_QA_REMARKS ?? "N/A",
  dateQaEnd: item.application_delegation?.DB_DATE_QA_END ?? "N/A",

  director: item.application_delegation?.DB_DIRECTOR ?? "N/A",
  directorDecision: item.application_delegation?.DB_DIRECTOR_DECISION ?? "N/A",
  directorRemarks: item.application_delegation?.DB_DIRECTOR_REMARKS ?? "N/A",
  dateDirectorEnd: item.application_delegation?.DB_DATE_DIRECTOR_END ?? "N/A",

  // ✅ Releasing Officer fields
  releasingOfficer: item.application_delegation?.DB_RELEASING_OFFICER ?? "N/A",
  releasingOfficerDecision:
    item.application_delegation?.DB_RELEASING_OFFICER_DECISION ?? "N/A",
  releasingOfficerRemarks:
    item.application_delegation?.DB_RELEASING_OFFICER_REMARKS ?? "N/A",
  dateReleasingOfficerEnd:
    item.application_delegation?.DB_RELEASING_OFFICER_END ?? "N/A",
});

export const getColorScheme = (darkMode) => {
  return darkMode
    ? {
        pageBg: "#0a0a0a",
        cardBg: "#0f0f0f",
        cardBorder: "#1a1a1a",
        cardBorderHover: "#2a2a2a",
        textPrimary: "#fff",
        textSecondary: "#999",
        textTertiary: "#666",
        inputBg: "#1a1a1a",
        inputBorder: "#2a2a2a",
        buttonSecondaryBg: "#1a1a1a",
        buttonSecondaryBorder: "#2a2a2a",
        buttonSecondaryBgHover: "#222",
        buttonSecondaryBorderHover: "#333",
        tableBg: "#0f0f0f",
        tableRowEven: "#0a0a0a",
        tableRowOdd: "#0f0f0f",
        tableRowHover: "#151515",
        tableBorder: "#1a1a1a",
        tableText: "#ccc",
        badgeBg: "#1a1a1a",
      }
    : {
        pageBg: "#f8f8f8",
        cardBg: "#ffffff",
        cardBorder: "#e5e5e5",
        cardBorderHover: "#d0d0d0",
        textPrimary: "#000",
        textSecondary: "#666",
        textTertiary: "#999",
        inputBg: "#ffffff",
        inputBorder: "#e5e5e5",
        buttonSecondaryBg: "#f5f5f5",
        buttonSecondaryBorder: "#e5e5e5",
        buttonSecondaryBgHover: "#e5e5e5",
        buttonSecondaryBorderHover: "#d0d0d0",
        tableBg: "#ffffff",
        tableRowEven: "#ffffff",
        tableRowOdd: "#fafafa",
        tableRowHover: "#f0f0f0",
        tableBorder: "#e5e5e5",
        tableText: "#333",
        badgeBg: "#f5f5f5",
      };
};
