export const getColorScheme = (darkMode) =>
  darkMode
    ? {
        pageBg: "#0a0a0a",
        cardBg: "#0f0f0f",
        cardBorder: "#1a1a1a",
        cardBorderHover: "#2a2a2a",
        textPrimary: "#fff",
        textSecondary: "#999",
        textTertiary: "#666",
        inputBg: "#1a1a1a",
        inputBorder: "#2a2a2a",
        buttonSecondaryBg: "#1a1a1a",
        buttonSecondaryBorder: "#2a2a2a",
        buttonSecondaryBgHover: "#222",
        buttonSecondaryBorderHover: "#333",
        tableBg: "#0f0f0f",
        tableRowEven: "#0a0a0a",
        tableRowOdd: "#0f0f0f",
        tableRowHover: "#151515",
        tableBorder: "#1a1a1a",
        tableText: "#ccc",
        badgeBg: "#1a1a1a",
      }
    : {
        pageBg: "#f8f8f8",
        cardBg: "#ffffff",
        cardBorder: "#e5e5e5",
        cardBorderHover: "#d0d0d0",
        textPrimary: "#000",
        textSecondary: "#666",
        textTertiary: "#999",
        inputBg: "#ffffff",
        inputBorder: "#e5e5e5",
        buttonSecondaryBg: "#f5f5f5",
        buttonSecondaryBorder: "#e5e5e5",
        buttonSecondaryBgHover: "#e5e5e5",
        buttonSecondaryBorderHover: "#d0d0d0",
        tableBg: "#ffffff",
        tableRowEven: "#ffffff",
        tableRowOdd: "#fafafa",
        tableRowHover: "#f0f0f0",
        tableBorder: "#e5e5e5",
        tableText: "#333",
        badgeBg: "#f5f5f5",
      };
