export const getColorScheme = (darkMode) =>
  darkMode
    ? {
        pageBg: "#0d0d0d",
        cardBg: "#1a1a1a",
        cardBorder: "#333333",
        cardBorderHover: "#454545",
        textPrimary: "#f5f5f5",
        textSecondary: "#b0b0b0",
        textTertiary: "#868686",
        inputBg: "#242424",
        inputBorder: "#3a3a3a",
        buttonSecondaryBg: "#242424",
        buttonSecondaryBorder: "#3a3a3a",
        buttonSecondaryBgHover: "#2e2e2e",
        buttonSecondaryBorderHover: "#454545",
        tableBg: "#1a1a1a",
        tableRowEven: "#181818",
        tableRowOdd: "#1e1e1e",
        tableRowHover: "#272727",
        tableBorder: "#333333",
        tableText: "#dcdcdc",
        badgeBg: "#2a2a2a",
      }
    : {
        pageBg: "#f8f8f8",
        cardBg: "#ffffff",
        cardBorder: "#e5e5e5",
        cardBorderHover: "#d0d0d0",
        textPrimary: "#000",
        textSecondary: "#666",
        textTertiary: "#999",
        inputBg: "#ffffff",
        inputBorder: "#e5e5e5",
        buttonSecondaryBg: "#f5f5f5",
        buttonSecondaryBorder: "#e5e5e5",
        buttonSecondaryBgHover: "#e5e5e5",
        buttonSecondaryBorderHover: "#d0d0d0",
        tableBg: "#ffffff",
        tableRowEven: "#ffffff",
        tableRowOdd: "#fafafa",
        tableRowHover: "#f0f0f0",
        tableBorder: "#e5e5e5",
        tableText: "#333",
        badgeBg: "#f5f5f5",
      };