export const tableColumns = [
  { key: "dtn", label: "DTN", width: "180px" },
  // ✅ Compliance Deadline — rendered only when activeTab === "Compliance"
  { key: "deadlineDate", label: "Compliance Deadline", width: "180px", complianceOnly: true },
  { key: "estCat", label: "Category", width: "120px" },
  { key: "ltoCompany", label: "LTO Company", width: "200px" },
  { key: "ltoAdd", label: "LTO Address", width: "200px" },
  { key: "eadd", label: "Email", width: "180px" },
  { key: "tin", label: "TIN", width: "120px" },
  { key: "contactNo", label: "Contact No.", width: "130px" },
  { key: "ltoNo", label: "LTO No.", width: "130px" },
  { key: "validity", label: "Validity", width: "120px" },
  { key: "prodBrName", label: "Brand Name", width: "180px" },
  { key: "prodGenName", label: "Generic Name", width: "180px" },
  { key: "prodDosStr", label: "Dosage Strength", width: "140px" },
  { key: "prodDosForm", label: "Dosage Form", width: "130px" },
  { key: "prodClassPrescript", label: "Prescription", width: "120px" },
  { key: "prodEssDrugList", label: "Essential Drug", width: "130px" },
  { key: "prodPharmaCat", label: "Pharma Category", width: "140px" },
  { key: "prodManu", label: "Manufacturer", width: "180px" },
  { key: "prodManuAdd", label: "Mfr. Address", width: "180px" },
  { key: "prodManuCountry", label: "Mfr. Country", width: "130px" },
  { key: "prodTrader", label: "Trader", width: "160px" },
  { key: "prodTraderCountry", label: "Trader Country", width: "130px" },
  { key: "prodImporter", label: "Importer", width: "160px" },
  { key: "prodImporterCountry", label: "Importer Country", width: "140px" },
  { key: "prodDistri", label: "Distributor", width: "160px" },
  { key: "prodDistriCountry", label: "Distri. Country", width: "140px" },
  { key: "prodDistriShelfLife", label: "Shelf Life", width: "110px" },
  { key: "packaging", label: "Packaging", width: "140px" },
  { key: "expiryDate", label: "Expiry Date", width: "120px" },
  { key: "regNo", label: "Reg. No.", width: "130px" },
  { key: "appType", label: "App Type", width: "120px" },
  { key: "motherAppType", label: "Mother App Type", width: "140px" },
  { key: "oldRsn", label: "Old RSN", width: "120px" },
  { key: "ammend1", label: "Amendment 1", width: "150px" },
  { key: "ammend2", label: "Amendment 2", width: "150px" },
  { key: "ammend3", label: "Amendment 3", width: "150px" },
  { key: "prodCat", label: "Product Category", width: "140px" },
  { key: "certification", label: "Certification", width: "150px" },
  { key: "fee", label: "Fee", width: "100px" },
  { key: "lrf", label: "LRF", width: "100px" },
  { key: "surc", label: "SURC", width: "100px" },
  { key: "total", label: "Total", width: "100px" },
  { key: "orNo", label: "OR No.", width: "120px" },
  { key: "dateIssued", label: "Date Issued", width: "130px" },
  { key: "dateReceivedFdac", label: "Date Rcvd FDAC", width: "140px" },
  { key: "dateReceivedCent", label: "Date Rcvd Central", width: "150px" },
  { key: "mo", label: "MO", width: "100px" },
  { key: "file", label: "File", width: "150px" },
  { key: "secpa", label: "SECPA", width: "120px" },
  { key: "secpaExpDate", label: "SECPA Exp Date", width: "150px" },
  { key: "secpaIssuedOn", label: "SECPA Issued On", width: "150px" },
  { key: "deckingSched", label: "Decking Sched", width: "140px" },
  { key: "eval", label: "Evaluator", width: "130px" },
  { key: "dateDeck", label: "Date Deck", width: "120px" },
  { key: "remarks1", label: "Remarks", width: "180px" },
  { key: "dateRemarks", label: "Date Remarks", width: "130px" },
  { key: "class", label: "Class", width: "110px" },
  { key: "dateReleased", label: "Date Released", width: "130px" },
  { key: "typeDocReleased", label: "Type Doc Released", width: "150px" },
  { key: "attaReleased", label: "Atta Released", width: "150px" },
  { key: "cprCond", label: "CPR Condition", width: "200px" },
  // cprCondRemarks is intentionally wide (600px) and wraps text
  { key: "cprCondRemarks", label: "CPR Cond Remarks", width: "600px", wrap: true },
  { key: "cprCondAddRemarks", label: "CPR Cond Add Remarks", width: "200px" },
  { key: "appStatus", label: "Status", width: "130px" },
  { key: "appRemarks", label: "App Remarks", width: "200px" },
  { key: "dbTimelineCitizenCharter", label: "Timeline (Days)", width: "130px" },
  { key: "statusTimeline", label: "Status Timeline", width: "160px" },
  { key: "userUploader", label: "Uploaded By", width: "140px" },
  { key: "uploadedAt", label: "Uploaded At", width: "140px" },
];

export const COLUMN_DB_KEY_MAP = {
  dtn:                    "DB_DTN",
  estCat:                 "DB_EST_CAT",
  ltoCompany:             "DB_EST_LTO_COMP",
  ltoAdd:                 "DB_EST_LTO_ADD",
  eadd:                   "DB_EST_EADD",
  tin:                    "DB_EST_TIN",
  contactNo:              "DB_EST_CONTACT_NO",
  ltoNo:                  "DB_EST_LTO_NO",
  validity:               "DB_EST_VALIDITY",
  prodBrName:             "DB_PROD_BR_NAME",
  prodGenName:            "DB_PROD_GEN_NAME",
  prodDosStr:             "DB_PROD_DOS_STR",
  prodDosForm:            "DB_PROD_DOS_FORM",
  prodClassPrescript:     "DB_PROD_CLASS_PRESCRIP",
  prodEssDrugList:        "DB_PROD_ESS_DRUG_LIST",
  prodPharmaCat:          "DB_PROD_PHARMA_CAT",
  prodManu:               "DB_PROD_MANU",
  prodManuAdd:            "DB_PROD_MANU_ADD",
  prodManuCountry:        "DB_PROD_MANU_COUNTRY",
  prodTrader:             "DB_PROD_TRADER",
  prodTraderCountry:      "DB_PROD_TRADER_COUNTRY",
  prodImporter:           "DB_PROD_IMPORTER",
  prodImporterCountry:    "DB_PROD_IMPORTER_COUNTRY",
  prodDistri:             "DB_PROD_DISTRI",
  prodDistriCountry:      "DB_PROD_DISTRI_COUNTRY",
  prodDistriShelfLife:    "DB_PROD_DISTRI_SHELF_LIFE",
  packaging:              "DB_PACKAGING",
  expiryDate:             "DB_EXPIRY_DATE",
  regNo:                  "DB_REG_NO",
  appType:                "DB_APP_TYPE",
  motherAppType:          "DB_MOTHER_APP_TYPE",
  oldRsn:                 "DB_OLD_RSN",
  // ── New columns ──────────────────────────────────────────────────────────
  ammend1:                "DB_AMMEND_1",
  ammend2:                "DB_AMMEND_2",
  ammend3:                "DB_AMMEND_3",
  prodCat:                "DB_PROD_CAT",
  certification:          "DB_CERTIFICATION",
  fee:                    "DB_FEE",
  lrf:                    "DB_LRF",
  surc:                   "DB_SURC",
  total:                  "DB_TOTAL",
  orNo:                   "DB_OR_NO",
  dateIssued:             "DB_DATE_ISSUED",
  dateReceivedFdac:       "DB_DATE_RECEIVED_FDAC",
  dateReceivedCent:       "DB_DATE_RECEIVED_CENT",
  mo:                     "DB_MO",
  file:                   "DB_FILE",
  secpa:                  "DB_SECPA",
  secpaExpDate:           "DB_SECPA_EXP_DATE",
  secpaIssuedOn:          "DB_SECPA_ISSUED_ON",
  deckingSched:           "DB_DECKING_SCHED",
  eval:                   "DB_EVAL",
  dateDeck:               "DB_DATE_DECK",
  remarks1:               "DB_REMARKS_1",
  dateRemarks:            "DB_DATE_REMARKS",
  class:                  "DB_CLASS",
  dateReleased:           "DB_DATE_RELEASED",
  typeDocReleased:        "DB_TYPE_DOC_RELEASED",
  attaReleased:           "DB_ATTA_RELEASED",
  cprCond:                "DB_CPR_COND",
  cprCondRemarks:         "DB_CPR_COND_REMARKS",
  cprCondAddRemarks:      "DB_CPR_COND_ADD_REMARKS",
  appStatus:              "DB_APP_STATUS",
  appRemarks:             "DB_APP_REMARKS",
  dbTimelineCitizenCharter: "DB_TIMELINE_CITIZEN_CHARTER",
  userUploader:           "DB_USER_UPLOADER",
  uploadedAt:             "DB_DATE_EXCEL_UPLOAD",
};