export const mapWorkflowTask = (task, index) => {
  const m = task.main_db || {};
  const d = task.application_delegation || {};
  return {
    id: task.id ?? m.DB_ID ?? index + 1,
    dtn: m.DB_DTN ?? "N/A",
    estCat: m.DB_EST_CAT ?? "N/A",
    ltoComp: m.DB_EST_LTO_COMP ?? "N/A",
    ltoCompany: m.DB_EST_LTO_COMP ?? "N/A",
    ltoAdd: m.DB_EST_LTO_ADD ?? "N/A",
    eadd: m.DB_EST_EADD ?? "N/A",
    tin: m.DB_EST_TIN ?? "N/A",
    contactNo: m.DB_EST_CONTACT_NO ?? "N/A",
    ltoNo: m.DB_EST_LTO_NO ?? "N/A",
    validity: m.DB_EST_VALIDITY ?? "N/A",
    prodBrName: m.DB_PROD_BR_NAME ?? "N/A",
    prodGenName: m.DB_PROD_GEN_NAME ?? "N/A",
    prodDosStr: m.DB_PROD_DOS_STR ?? "N/A",
    prodDosForm: m.DB_PROD_DOS_FORM ?? "N/A",
    prodClassPrescript: m.DB_PROD_CLASS_PRESCRIP ?? "N/A",
    prodEssDrugList: m.DB_PROD_ESS_DRUG_LIST ?? "N/A",
    prodPharmaCat: m.DB_PROD_PHARMA_CAT ?? "N/A",
    manufacturer: m.DB_PROD_MANU ?? "N/A",
    prodManu: m.DB_PROD_MANU ?? "N/A",
    prodManuAdd: m.DB_PROD_MANU_ADD ?? "N/A",
    prodManuTin: m.DB_PROD_MANU_TIN ?? "N/A",
    prodManuLtoNo: m.DB_PROD_MANU_LTO_NO ?? "N/A",
    prodManuCountry: m.DB_PROD_MANU_COUNTRY ?? "N/A",
    prodTrader: m.DB_PROD_TRADER ?? "N/A",
    prodTraderAdd: m.DB_PROD_TRADER_ADD ?? "N/A",
    prodTraderTin: m.DB_PROD_TRADER_TIN ?? "N/A",
    prodTraderLtoNo: m.DB_PROD_TRADER_LTO_NO ?? "N/A",
    prodTraderCountry: m.DB_PROD_TRADER_COUNTRY ?? "N/A",
    prodRepacker: m.DB_PROD_REPACKER ?? "N/A",
    prodRepackerAdd: m.DB_PROD_REPACKER_ADD ?? "N/A",
    prodRepackerTin: m.DB_PROD_REPACKER_TIN ?? "N/A",
    prodRepackerLtoNo: m.DB_PROD_REPACKER_LTO_NO ?? "N/A",
    prodRepackerCountry: m.DB_PROD_REPACKER_COUNTRY ?? "N/A",
    prodImporter: m.DB_PROD_IMPORTER ?? "N/A",
    prodImporterAdd: m.DB_PROD_IMPORTER_ADD ?? "N/A",
    prodImporterTin: m.DB_PROD_IMPORTER_TIN ?? "N/A",
    prodImporterLtoNo: m.DB_PROD_IMPORTER_LTO_NO ?? "N/A",
    prodImporterCountry: m.DB_PROD_IMPORTER_COUNTRY ?? "N/A",
    prodDistri: m.DB_PROD_DISTRI ?? "N/A",
    prodDistriAdd: m.DB_PROD_DISTRI_ADD ?? "N/A",
    prodDistriTin: m.DB_PROD_DISTRI_TIN ?? "N/A",
    prodDistriLtoNo: m.DB_PROD_DISTRI_LTO_NO ?? "N/A",
    prodDistriCountry: m.DB_PROD_DISTRI_COUNTRY ?? "N/A",
    prodDistriShelfLife: m.DB_PROD_DISTRI_SHELF_LIFE ?? "N/A",
    storageCond: m.DB_STORAGE_COND ?? "N/A",
    packaging: m.DB_PACKAGING ?? "N/A",
    suggRp: m.DB_SUGG_RP ?? "N/A",
    noSample: m.DB_NO_SAMPLE ?? "N/A",
    expiryDate: m.DB_EXPIRY_DATE ?? "N/A",
    cprValidity: m.DB_CPR_VALIDITY ?? "N/A",
    regNo: m.DB_REG_NO ?? "N/A",
    appType: m.DB_APP_TYPE ?? "N/A",
    motherAppType: m.DB_MOTHER_APP_TYPE ?? "N/A",
    oldRsn: m.DB_OLD_RSN ?? "N/A",
    ammend1: m.DB_AMMEND1 ?? "N/A",
    ammend2: m.DB_AMMEND2 ?? "N/A",
    ammend3: m.DB_AMMEND3 ?? "N/A",
    prodCat: m.DB_PROD_CAT ?? "N/A",
    certification: m.DB_CERTIFICATION ?? "N/A",
    fee: m.DB_FEE ?? "N/A",
    lrf: m.DB_LRF ?? "N/A",
    surc: m.DB_SURC ?? "N/A",
    total: m.DB_TOTAL ?? "N/A",
    orNo: m.DB_OR_NO ?? "N/A",
    dateIssued: m.DB_DATE_ISSUED ?? "N/A",
    dateReceivedFdac: m.DB_DATE_RECEIVED_FDAC ?? "N/A",
    dateReceivedCent: m.DB_DATE_RECEIVED_CENT ?? "N/A",
    mo: m.DB_MO ?? "N/A",
    file: m.DB_FILE ?? "N/A",
    secpa: m.DB_SECPA ?? "N/A",
    secpaExpDate: m.DB_SECPA_EXP_DATE ?? "N/A",
    secpaIssuedOn: m.DB_SECPA_ISSUED_ON ?? "N/A",
    deckingSched: m.DB_DECKING_SCHED ?? "N/A",
    eval: m.DB_EVAL ?? "N/A",
    dateDeck: m.DB_DATE_DECK ?? "N/A",
    remarks1: m.DB_REMARKS_1 ?? "N/A",
    dateRemarks: m.DB_DATE_REMARKS ?? "N/A",
    class: m.DB_CLASS ?? "N/A",
    dateReleased: m.DB_DATE_RELEASED ?? "N/A",
    typeDocReleased: m.DB_TYPE_DOC_RELEASED ?? "N/A",
    attaReleased: m.DB_ATTA_RELEASED ?? "N/A",
    cprCond: m.DB_CPR_COND ?? "N/A",
    cprCondRemarks: m.DB_CPR_COND_REMARKS ?? "N/A",
    cprCondAddRemarks: m.DB_CPR_COND_ADD_REMARKS ?? "N/A",
    appStatus: m.DB_APP_STATUS ?? "N/A",
    appRemarks: m.DB_APP_REMARKS ?? "N/A",
    trash: m.DB_TRASH ?? "N/A",
    trashDateEncoded: m.DB_TRASH_DATE_ENCODED ?? "N/A",
    userUploader: m.DB_USER_UPLOADER ?? "N/A",
    uploadedAt: m.DB_DATE_EXCEL_UPLOAD ?? "N/A",
    dateExcelUpload: m.DB_DATE_EXCEL_UPLOAD ?? "N/A",
    pharmaProdCat: m.DB_PHARMA_PROD_CAT ?? "N/A",
    pharmaProdCatLabel: m.DB_PHARMA_PROD_CAT_LABEL ?? "N/A",
    isInPm: m.DB_IS_IN_PM ?? "N/A",
    dbTimelineCitizenCharter: m.DB_TIMELINE_CITIZEN_CHARTER ?? null,
    applicationStep: task.application_step,
    accomplishedDate: task.accomplished_date ?? "N/A",
    logCreatedAt: task.created_at ?? "N/A",
    decker: d.DB_DECKER ?? "N/A",
    deckerDecision: d.DB_DECKER_DECISION ?? "N/A",
    deckerRemarks: d.DB_DECKER_REMARKS ?? "N/A",
    dateDeckedEnd: d.DB_DATE_DECKED_END ?? "N/A",
    evaluator: d.DB_EVALUATOR ?? task.user_name ?? "N/A",
    evalDecision: d.DB_EVAL_DECISION ?? "N/A",
    evalRemarks: d.DB_EVAL_REMARKS ?? "N/A",
    dateEvalEnd: d.DB_DATE_EVAL_END ?? "N/A",
    checker: d.DB_CHECKER ?? "N/A",
    checkerDecision: d.DB_CHECKER_DECISION ?? "N/A",
    checkerRemarks: d.DB_CHECKER_REMARKS ?? "N/A",
    dateCheckerEnd: d.DB_DATE_CHECKER_END ?? "N/A",
    supervisor: d.DB_SUPERVISOR ?? "N/A",
    supervisorDecision: d.DB_SUPERVISOR_DECISION ?? "N/A",
    supervisorRemarks: d.DB_SUPERVISOR_REMARKS ?? "N/A",
    dateSupervisorEnd: d.DB_DATE_SUPERVISOR_END ?? "N/A",
    qa: d.DB_QA ?? "N/A",
    qaDecision: d.DB_QA_DECISION ?? "N/A",
    qaRemarks: d.DB_QA_REMARKS ?? "N/A",
    dateQaEnd: d.DB_DATE_QA_END ?? "N/A",
    director: d.DB_DIRECTOR ?? "N/A",
    directorDecision: d.DB_DIRECTOR_DECISION ?? "N/A",
    directorRemarks: d.DB_DIRECTOR_REMARKS ?? "N/A",
    dateDirectorEnd: d.DB_DATE_DIRECTOR_END ?? "N/A",
    releasingOfficer: d.DB_RELEASING_OFFICER ?? "N/A",
    releasingOfficerDecision: d.DB_RELEASING_OFFICER_DECISION ?? "N/A",
    releasingOfficerRemarks: d.DB_RELEASING_OFFICER_REMARKS ?? "N/A",
    dateReleasingOfficerEnd: d.DB_RELEASING_OFFICER_END ?? "N/A",
  };
};

export const getCurrentUser = () => {
  const s = localStorage.getItem("user") || sessionStorage.getItem("user");
  if (s) {
    try {
      const o = JSON.parse(s);
      return o.username || o.email || o.first_name || null;
    } catch {
      return s;
    }
  }
  return (
    localStorage.getItem("username") ||
    sessionStorage.getItem("username") ||
    null
  );
};
