export const COLORS = {
  cardBg: "#fff",
  cardBorder: "#D6D1CB",
  textPrimary: "#1C1A17",
  textSecondary: "#6B6560",
  textTertiary: "#9E9890",
  inputBg: "#F5F3EE",
  inputBorder: "#D6D1CB",
};

export const DECKER_DECISIONS = [
  "For Quality Evaluation",
  "For LRD Decking",
  "For OD Review",
  "For PRSDD Quality Evaluation",
];

export const DOCTRACK_DEFAULTS = {
  "For Quality Evaluation": "Forwarded to evaluator",
  "For LRD Decking": "Forwarded to LRD Decker",
  "For OD Review": "Forwarded to OD Review Staff",
  "For PRSDD Quality Evaluation": "Forwarded to PRSDD Quality Evaluation",
};

export const MOCK_RECORD = {
  dtn: "DTN-2024-00871",
  appStatus: "PENDING",
  processingType: "Regular",
  estCat: "Pharmaceutical",
  appType: "New Application",
  ltoComp: "Dela Cruz General Merchandise",
  ltoAdd: "123 Rizal St., Brgy. San Isidro, Majayjay, Laguna 4015",
  eadd: "juandelacruz@gmial.com",
  tin: "123-456-789-000",
  contactNo: "+63 917 234 5678",
  ltoNo: "LTO-2024-001234",
  validity: "2025-12-31",
  dateReceivedCent: "2025-02-12",
  dateReceivedFdac: "2025-02-14",
  dbTimelineCitizenCharter: "20",
  dateReleased: null,
  prodBrName: "AmoxiGen 500mg",
  prodGenName: "Amoxicillin",
  prodDosStr: "500mg",
  prodDosForm: "Capsule",
  prodClassPrescript: "Rx",
  prodEssDrugList: "Yes",
  prodDistriShelfLife: "24 months",
  prodPharmaCat: "Antibiotics",
  prodCat: "Human Use",
  file: "N/A",
  storageCond: "Store below 30°C",
  packaging: "10 capsules/blister, 10 blisters/box",
  expiryDate: "2027-02-12",
  suggRp: "P 5.00/capsule",
  noSample: "3",
  fee: "1,620.00",
  lrf: "100.00",
  surc: "50.00",
  total: "1,770.00",
  orNo: "OR-2025-004567",
  dateIssued: "2025-02-14",
  prodManu: "PharmaCo International Inc.",
  prodManuCountry: "Philippines",
  prodManuLtoNo: "LTO-MFG-2023-0089",
  prodManuTin: "200-123-456-000",
  prodManuAdd: "Lot 5 Blk 3, Laguna Technopark, Binan, Laguna",
  prodTrader: "N/A",
  prodTraderCountry: "N/A",
  prodTraderLtoNo: "N/A",
  prodTraderTin: "N/A",
  prodTraderAdd: "N/A",
  prodImporter: "N/A",
  prodImporterCountry: "N/A",
  prodImporterLtoNo: "N/A",
  prodImporterTin: "N/A",
  prodImporterAdd: "N/A",
  prodDistri: "Dela Cruz General Merchandise",
  prodDistriCountry: "Philippines",
  prodDistriLtoNo: "LTO-2024-001234",
  prodDistriTin: "123-456-789-000",
  prodDistriAdd: "123 Rizal St., Brgy. San Isidro, Majayjay, Laguna 4015",
  prodRepacker: "N/A",
  prodRepackerCountry: "N/A",
  prodRepackerLtoNo: "N/A",
  prodRepackerTin: "N/A",
  prodRepackerAdd: "N/A",
  regNo: "N/A",
  motherAppType: "N/A",
  oldRsn: "N/A",
  certification: "N/A",
  class: "N/A",
  mo: "N/A",
  typeDocReleased: "N/A",
  attaReleased: "N/A",
  secpa: "N/A",
  secpaExpDate: null,
  secpaIssuedOn: null,
  cprCond: "N/A",
  cprCondRemarks: "N/A",
  cprCondAddRemarks: "N/A",
  ammend1: "N/A",
  ammend2: "N/A",
  ammend3: "N/A",
  appRemarks: "Correction required on email and business name.",
  remarks1: "N/A",
};

export const ps = {
  card: {
    // background intentionally omitted — set by each component using dark-aware token
    border: "1px solid #D6D1CB",
    borderRadius: 12,
    boxShadow: "0 1px 4px rgba(0,0,0,0.07)",
    overflow: "hidden",
    marginBottom: "1rem",
  },
  cardHeader: {
    padding: "11px 16px",
    borderBottom: "1px solid #D6D1CB",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardHeaderTitle: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "#9E9890",
    textTransform: "uppercase",
    letterSpacing: "0.7px",
  },
  cardBody: { padding: "16px" },
  btn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontFamily: "inherit",
    fontSize: 12.5,
    fontWeight: 600,
    padding: "8px 14px",
    borderRadius: 9,
    border: "1px solid transparent",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  btnGhost: {
    background: "transparent",
    borderColor: "#B0AAA2",
    color: "#6B6560",
  },
  btnPrimary: { background: "#2C5F8A", borderColor: "#2C5F8A", color: "#fff" },
  btnDanger: {
    background: "transparent",
    borderColor: "#F7C1C1",
    color: "#A32D2D",
  },
  btnSuccess: { background: "#3B6D11", borderColor: "#3B6D11", color: "#fff" },
  sep: { height: 1, background: "#EFECEA", margin: "14px 0" },
  uploadZone: {
    border: "1.5px dashed #B0AAA2",
    borderRadius: 10,
    padding: 16,
    textAlign: "center",
    cursor: "pointer",
    marginTop: 4,
  },
  footer: {
    gridColumn: "1 / -1",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "12px 16px",
    // background intentionally omitted — set by CorrectionPage dark-aware token
    border: "1px solid #D6D1CB",
    borderRadius: 12,
    boxShadow: "0 1px 4px rgba(0,0,0,0.07)",
    flexWrap: "wrap",
  },
  fullRow: { gridColumn: "1 / -1" },
};