export const EDITABLE_FIELDS = [
  "estCat", "ltoNo", "tin", "eadd", "contactNo", "ltoAdd",
  "prodDosStr", "prodPharmaCat", "prodEssDrugList", "prodCat",
  "pharmaProdCat", "pharmaProdCatLabel", "file", "prodManu",
  "prodManuCountry", "prodManuLtoNo", "prodManuTin", "prodManuAdd",
  "prodTrader", "prodTraderCountry", "prodTraderLtoNo", "prodTraderTin",
  "prodTraderAdd", "prodImporter", "prodImporterCountry", "prodImporterLtoNo",
  "prodImporterTin", "prodImporterAdd", "prodDistri", "prodDistriCountry",
  "prodDistriLtoNo", "prodDistriTin", "prodDistriShelfLife", "prodDistriAdd",
  "prodRepacker", "prodRepackerCountry", "prodRepackerLtoNo", "prodRepackerTin",
  "prodRepackerAdd", "ltoCompany", "appType", "prodDosForm",
  "prodClassPrescript", "appStatus", "processingType", "appRemarks",
  "remarks1", "cprCond", "cprCondRemarks", "cprCondAddRemarks",
  "storageCond", "packaging", "suggRp", "noSample", "ammend1",
  "ammend2", "ammend3", "regNo", "motherAppType", "oldRsn",
  "certification", "class", "mo", "fee", "lrf", "surc", "total",
  "orNo", "secpa", "validity", "prodBrName", "prodGenName",
  "attaReleased",
  "dateReleased",
  "typeDocReleased",
  "secpaExpDate",
  "secpaIssuedOn",
  "dateIssued",
];

export const FIELD_LABEL_MAP = {
  estCat: "Category",
  ltoNo: "LTO No.",
  tin: "TIN",
  eadd: "Email",
  contactNo: "Contact No.",
  ltoAdd: "LTO Address",
  prodDosStr: "Dosage Strength",
  prodPharmaCat: "Pharma Category",
  prodEssDrugList: "Essential Drug",
  prodCat: "Product Category",
  pharmaProdCat: "Pharma Prod. Cat.",
  pharmaProdCatLabel: "Pharma Prod. Label",
  file: "File",
  prodManu: "Manufacturer",
  prodManuCountry: "Manufacturer Country",
  prodManuLtoNo: "Manufacturer LTO No.",
  prodManuTin: "Manufacturer TIN",
  prodManuAdd: "Manufacturer Address",
  prodTrader: "Trader",
  prodTraderCountry: "Trader Country",
  prodTraderLtoNo: "Trader LTO No.",
  prodTraderTin: "Trader TIN",
  prodTraderAdd: "Trader Address",
  prodImporter: "Importer",
  prodImporterCountry: "Importer Country",
  prodImporterLtoNo: "Importer LTO No.",
  prodImporterTin: "Importer TIN",
  prodImporterAdd: "Importer Address",
  prodDistri: "Distributor",
  prodDistriCountry: "Distributor Country",
  prodDistriLtoNo: "Distributor LTO No.",
  prodDistriTin: "Distributor TIN",
  prodDistriShelfLife: "Shelf Life",
  prodDistriAdd: "Distributor Address",
  prodRepacker: "Repacker",
  prodRepackerCountry: "Repacker Country",
  prodRepackerLtoNo: "Repacker LTO No.",
  prodRepackerTin: "Repacker TIN",
  prodRepackerAdd: "Repacker Address",
  ltoCompany: "LTO Company",
  appType: "Application Type",
  prodDosForm: "Dosage Form",
  prodClassPrescript: "Prescription",
  appStatus: "App Status",
  processingType: "Processing Type",
  appRemarks: "Application Remarks",
  remarks1: "General Remarks",
  cprCond: "CPR Condition",
  cprCondRemarks: "CPR Condition Remarks",
  cprCondAddRemarks: "CPR Condition Additional Remarks",
  storageCond: "Storage Condition",
  packaging: "Packaging",
  suggRp: "Suggested RP",
  noSample: "No. of Samples",
  ammend1: "Amendment 1",
  ammend2: "Amendment 2",
  ammend3: "Amendment 3",
  regNo: "Registration No.",
  motherAppType: "Mother App Type",
  oldRsn: "Old RSN",
  certification: "Certification",
  class: "Class",
  mo: "MO",
  fee: "Fee",
  lrf: "LRF",
  surc: "SURC",
  total: "Total",
  orNo: "OR No.",
  dateIssued: "Date Issued",
  secpa: "SECPA",
  validity: "LTO Validity", // ← CHANGED: was "Validity"
  attaReleased: "Attachment Released",
  dateReleased: "Date Released",
  typeDocReleased: "Type of Document Released",
  secpaExpDate: "SECPA Expiry Date",
  secpaIssuedOn: "SECPA Issued On",
  prodBrName: "Brand Name",
  prodGenName: "Generic Name",
  expiryDate: "Expiry Date", 
  cprValidity: "CPR Validity",    
};

export const FIELD_KEY_TO_DB = {
  prodBrName: "DB_PROD_BR_NAME",
  prodGenName: "DB_PROD_GEN_NAME",
  estCat: "DB_EST_CAT",
  ltoNo: "DB_EST_LTO_NO",
  tin: "DB_EST_TIN",
  eadd: "DB_EST_EADD",
  contactNo: "DB_EST_CONTACT_NO",
  ltoAdd: "DB_EST_LTO_ADD",
  ltoCompany: "DB_EST_LTO_COMP",
  prodDosStr: "DB_PROD_DOS_STR",
  prodPharmaCat: "DB_PROD_PHARMA_CAT",
  prodEssDrugList: "DB_PROD_ESS_DRUG_LIST",
  prodCat: "DB_PROD_CAT",
  pharmaProdCat: "DB_PHARMA_PROD_CAT",
  pharmaProdCatLabel: "DB_PHARMA_PROD_CAT_LABEL",
  file: "DB_FILE",
  prodManu: "DB_PROD_MANU",
  prodManuCountry: "DB_PROD_MANU_COUNTRY",
  prodManuLtoNo: "DB_PROD_MANU_LTO_NO",
  prodManuTin: "DB_PROD_MANU_TIN",
  prodManuAdd: "DB_PROD_MANU_ADD",
  prodTrader: "DB_PROD_TRADER",
  prodTraderCountry: "DB_PROD_TRADER_COUNTRY",
  prodTraderLtoNo: "DB_PROD_TRADER_LTO_NO",
  prodTraderTin: "DB_PROD_TRADER_TIN",
  prodTraderAdd: "DB_PROD_TRADER_ADD",
  prodImporter: "DB_PROD_IMPORTER",
  prodImporterCountry: "DB_PROD_IMPORTER_COUNTRY",
  prodImporterLtoNo: "DB_PROD_IMPORTER_LTO_NO",
  prodImporterTin: "DB_PROD_IMPORTER_TIN",
  prodImporterAdd: "DB_PROD_IMPORTER_ADD",
  prodDistri: "DB_PROD_DISTRI",
  prodDistriCountry: "DB_PROD_DISTRI_COUNTRY",
  prodDistriLtoNo: "DB_PROD_DISTRI_LTO_NO",
  prodDistriTin: "DB_PROD_DISTRI_TIN",
  prodDistriShelfLife: "DB_PROD_DISTRI_SHELF_LIFE",
  prodDistriAdd: "DB_PROD_DISTRI_ADD",
  prodRepacker: "DB_PROD_REPACKER",
  prodRepackerCountry: "DB_PROD_REPACKER_COUNTRY",
  prodRepackerLtoNo: "DB_PROD_REPACKER_LTO_NO",
  prodRepackerTin: "DB_PROD_REPACKER_TIN",
  prodRepackerAdd: "DB_PROD_REPACKER_ADD",
  appType: "DB_APP_TYPE",
  prodDosForm: "DB_PROD_DOS_FORM",
  prodClassPrescript: "DB_PROD_CLASS_PRESCRIP",
  appStatus: "DB_APP_STATUS",
  processingType: "DB_PROCESSING_TYPE",
  appRemarks: "DB_APP_REMARKS",
  remarks1: "DB_REMARKS_1",
  cprCond: "DB_CPR_COND",
  cprCondRemarks: "DB_CPR_COND_REMARKS",
  cprCondAddRemarks: "DB_CPR_COND_ADD_REMARKS",
  storageCond: "DB_STORAGE_COND",
  packaging: "DB_PACKAGING",
  suggRp: "DB_SUGG_RP",
  noSample: "DB_NO_SAMPLE",
  ammend1: "DB_AMMEND1",
  ammend2: "DB_AMMEND2",
  ammend3: "DB_AMMEND3",
  regNo: "DB_REG_NO",
  motherAppType: "DB_MOTHER_APP_TYPE",
  oldRsn: "DB_OLD_RSN",
  certification: "DB_CERTIFICATION",
  class: "DB_CLASS",
  mo: "DB_MO",
  fee: "DB_FEE",
  lrf: "DB_LRF",
  surc: "DB_SURC",
  total: "DB_TOTAL",
  orNo: "DB_OR_NO",
  dateIssued: "DB_DATE_ISSUED",
  secpa: "DB_SECPA",
  validity: "DB_EST_VALIDITY", // ← CHANGED: was "DB_VALIDITY" (column does not exist)
  attaReleased: "DB_ATTA_RELEASED",
  dateReleased: "DB_DATE_RELEASED",
  typeDocReleased: "DB_TYPE_DOC_RELEASED",
  secpaExpDate: "DB_SECPA_EXP_DATE",
  secpaIssuedOn: "DB_SECPA_ISSUED_ON",
  expiryDate: "DB_EXPIRY_DATE",
  cprValidity: "DB_CPR_VALIDITY",
};