// FILE: src/components/groupManagement/useColors.js

export const useColors = (darkMode) => {
  return darkMode
    ? {
        pageBg: "#0a0a0a",
        cardBg: "#161616",
        cardBorder: "#252525",
        textPrimary: "#fff",
        textSecondary: "#999",
        textTertiary: "#555",
        inputBg: "#1a1a1a",
        inputBorder: "#2a2a2a",
        rowHover: "#1e1e1e",
        rowBorder: "#222",
        selectedBg: "#1f1f1f",
        selectedBorder: "#3a3a3a",
        btnPrimary: "#6366f1",
        btnPrimaryHover: "#5558e3",
        btnDanger: "#ef4444",
        btnDangerHover: "#dc2626",
        btnGhost: "transparent",
        btnGhostBorder: "#333",
        btnGhostText: "#999",
        modalOverlay: "rgba(0,0,0,0.6)",
        modalBg: "#1e1e1e",
        modalBorder: "#333",
        toastSuccess: { bg: "#16a34a", text: "#fff" },
        toastError: { bg: "#dc2626", text: "#fff" },
        dropdownBg: "#1e1e1e",
        dropdownBorder: "#2a2a2a",
        dropdownHover: "#2a2a2a",
        badgeActive: { bg: "#0a2a0a", text: "#22c55e" },
        badgeInactive: { bg: "#1a1a1a", text: "#666" },
        tabActive: "#6366f1",
        tabInactive: "#333",
      }
    : {
        pageBg: "#f8f8f8",
        cardBg: "#ffffff",
        cardBorder: "#e5e5e5",
        textPrimary: "#111",
        textSecondary: "#555",
        textTertiary: "#999",
        inputBg: "#fff",
        inputBorder: "#ddd",
        rowHover: "#fafafa",
        rowBorder: "#eee",
        selectedBg: "#f0f4ff",
        selectedBorder: "#6366f1",
        btnPrimary: "#6366f1",
        btnPrimaryHover: "#5558e3",
        btnDanger: "#ef4444",
        btnDangerHover: "#dc2626",
        btnGhost: "transparent",
        btnGhostBorder: "#ddd",
        btnGhostText: "#666",
        modalOverlay: "rgba(0,0,0,0.4)",
        modalBg: "#fff",
        modalBorder: "#e5e5e5",
        toastSuccess: { bg: "#16a34a", text: "#fff" },
        toastError: { bg: "#dc2626", text: "#fff" },
        dropdownBg: "#fff",
        dropdownBorder: "#e5e5e5",
        dropdownHover: "#f5f5f5",
        badgeActive: { bg: "#dcfce7", text: "#16a34a" },
        badgeInactive: { bg: "#f3f4f6", text: "#6b7280" },
        tabActive: "#6366f1",
        tabInactive: "#e5e5e5",
      };
};